name: manual

on:
  push:
    branches:
    - main
    paths:
    - 'manual/**'
  pull_request:
    branches:
    - develop

  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and deploy manual
    runs-on: ubuntu-latest
  
    steps:
    - name: Install Linux Deps
      run: sudo apt install texlive-xetex

    - name: Build manual
      working-directory: ${{github.workspace}}/manual
      run: |
        pwd
        ls
        make

    - name: Deploy manual
      uses: appleboy/scp-action@master
      with:
        host: ccrma-gate.stanford.edu
        username: jatin
        password: ${{ secrets.CCRMA_PASS }}
        source: "manual/ChowMatrixManual.pdf"
        target: "~/Library/Web/chowdsp/Products"
